# PyInstaller spec for Space Trader.
#
# Build with:
#   ./venv/bin/pyinstaller spacetrader.spec
#
# Produces a windowed (no console) standalone build:
#   - macOS: dist/Space Trader.app
#   - Windows: dist/Space Trader/Space Trader.exe
#   - Linux:   dist/Space Trader/Space Trader
#
# Settings, saves, and logs are written to an OS-appropriate per-user
# data directory (see src/paths.py), not next to the executable, since
# the bundle itself may be read-only (a signed macOS .app) or installed
# somewhere requiring admin rights to write to (Program Files).
#
# Icon: generated by scripts/generate_icon.py into assets/icon/
# (icon.ico for Windows, icon.icns for macOS - EXE's icon= is ignored
# on Linux, which has no single-file icon format PyInstaller sets here).
import os
import sys

icon_dir = os.path.join(os.path.dirname(os.path.abspath(SPEC)), 'assets', 'icon')
exe_icon = os.path.join(icon_dir, 'icon.ico') if sys.platform == 'win32' else None
app_icon = os.path.join(icon_dir, 'icon.icns')

a = Analysis(
    ['launcher.py'],
    pathex=[],
    binaries=[],
    datas=[('assets', 'assets')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

# onedir build: the executable references binaries/data alongside it rather
# than unpacking a single file to a temp dir on every launch (faster start,
# and the only sensible option for a macOS .app bundle per PyInstaller).
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Space Trader',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=exe_icon,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Space Trader',
)

app = BUNDLE(
    coll,
    name='Space Trader.app',
    icon=app_icon,
    bundle_identifier='com.spacetrader.game',
    info_plist={
        'CFBundleName': 'Space Trader',
        'CFBundleDisplayName': 'Space Trader',
        'CFBundleShortVersionString': '1.0.0',
        'NSHighResolutionCapable': True,
    },
)
